### PR TITLE
Equipment HotSpot Mapped Image

### PR DESCRIPTION
**Pull request by karimkawambwa**
##### What does this PR do?

Implement Equipment HotSpot Mapped Image

##### Screenshots?

Screen Shot 2019-06-13 at 12 35 15 PM

### CODE REVIEW

**Comment by karimkawambwa** [comment]
@nerdlet I will need data for this

**Comment by nerdlet** [comment]
@karimkawambwa Working on getting the data.

**Comment by nerdlet** [comment]
@karimkawambwa 
So, noticed this on my end...
1. The background photo height is way too long...maybe try to reduce the height of it to match the height of  on the zeplin designs ` 783px`

2. Could we also reduce the height of the popup to a much reasonable height? This will depend heavily on the height of the background image

image

Otherwise  LGTM
@kilemensi Could you test this out, just to confirm we are getting the same thing

**Comment by karimkawambwa** [comment]
Merging this, talked to @nerdlet on slack, it is at a good point to merge.

**Pull request merged**
