### PR TITLE
Blasts HUD

### PR DESCRIPTION
**Pull request by karimkawambwa**
##### What does this PR do?

Make Landing page blasts information HUD Desktop and Mobile compatible.

##### Screenshots?

Screen Shot 2019-06-04 at 4 22 29 PM
Screen Shot 2019-06-04 at 4 22 41 PM

### CODE REVIEW

**Review by kilemensi — COMMENTED** [review]
Looks good @karimkawambwa. Only issues I noticed:

1. The dots are too close together
Screenshot from 2019-06-10 13-39-12 vs
Screenshot from 2019-06-10 13-39-31
2. Heading needs to have a small underlining
Screenshot_2019-06-10 Zeplin - Project

**Review by nerdlet — COMMENTED** [review]
@karimkawambwa  LGTM...althought i did noticed that on medium devices we have this: 
image

and this:
image

**Comment by karimkawambwa** [comment]
@nerdlet I think its ready for another review

cc @kilemensi

**Comment by kilemensi** [comment]
Looks good for `sm` and `lg` screens @karimkawambwa.

1. **Blasts Recorded** still needs that underlining per design
Screenshot_2019-06-10 Zeplin - Project
2. `md` screen looks off
Screenshot_2019-06-12 SeaSensors sensors AFRICA

**Comment by karimkawambwa** [comment]
@kilemensi one more review cc @nerdlet

**Comment by nerdlet** [comment]
@karimkawambwa 

For the small devices, noticed the spacing between the typography and the svg was a bit off
image

and this as well
image

Otherwise..looks good to me

**Pull request merged**
